name: Age In Place Puerto Rico
favicon: null
layout_spectrum: 0.3527558767236769
typography_spectrum: 0.1616985818836838
title: Age In Place Puerto Rico
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5009521183092147
  lightness: 0.10167921939864755
  saturation: 0.2355045834556222
  rhythmicContrast: 0.16781000257469714
purpose: []
